import { Prefix } from '../constants';

export const FETCH_USER_RIGHTS_REQUEST = `${Prefix.RIGHTS}/FETCH_USER_RIGHTS_REQUEST`;
export const FETCH_USER_RIGHTS_SUCCESS = `${Prefix.RIGHTS}/FETCH_USER_RIGHTS_SUCCESS`;
export const FETCH_USER_RIGHTS_ERROR = `${Prefix.RIGHTS}/FETCH_USER_RIGHTS_ERROR`;
